name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build for Chrome
        run: |
          npm run clean
          npm run build:firefox
          mkdir -p dist
          zip -r dist/no-toxicity-extension-chrome.zip . -x "node_modules/*" ".git/*" "dist/*" ".github/"

      - name: Build for Firefox
        run: |
          npm run clean
          npm run build:chrome
          zip -r dist/no-toxicity-extension-firefox.zip . -x "node_modules/*" ".git/*" "dist/*" ".github/"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extensions
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: build_and_package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: extensions
          path: dist/

      - name: Calculate version number
        run: echo "VERSION=v1.0.$(git rev-list --count main)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          make_latest: true
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
